<?php

use think\facade\Route;
//Route::bind('admin');
Route::rule('login','Admin/login');
Route::rule('logout','Admin/logout');
Route::rule('admin_detail/[:admin_id]','Admin/add_edit_admin');
Route::rule('admin_index','Admin/admin_list');
Route::rule('admin_shanchu','Admin/admin_del');
Route::rule('admin_qx','Admin/admin_role');
Route::rule('admin_qx_edit/[:role_id]','Admin/add_edit_role');
Route::rule('admin_qx_del/[:role_id]','Admin/roleDel');
Route::rule('admin_quanxian','Admin/right_list');
Route::rule('con_action','Admin/ajax_get_action');
Route::rule('admin_quanxian_edit/[:id]','Admin/add_edit_right');
Route::rule('admin_rizhi','Admin/admin_log');
Route::rule('/','Index/index');
Route::rule('index_dc','Index/export_index');
Route::rule('tableVal','Index/changeTableVal');
Route::rule('getCategory','Index/get_category');
Route::rule('get_diqu','Index/get_region');
Route::rule('shanchu','Index/public_delete');
/********************{user控制器}********************/
Route::rule('user_index','User/index');
Route::rule('user_dc','User/export_user');
Route::rule('user_xq/:user_id','User/detail');
//Route::rule('user_td/:user_id','User/user_team');
//Route::rule('zijin/:user_id','User/account_edit');
//Route::rule('zj_mx/:user_id','User/account_log');
//Route::rule('user_dizhi/:user_id','User/address');
//Route::rule('add_user','User/add_user');
//Route::rule('user_qiandao','User/user_sign');
/********************{items项目管理控制器}********************/
Route::rule('bq_list','Items/tag_list');
Route::rule('voucher_list','Voucher/voucher_list');
Route::rule('add_edit_voucher','Voucher/add_edit_voucher');
Route::rule('invoice_list','Voucher/invoice_list');
Route::rule('pay_list/[:id]','Voucher/pay_list');
Route::rule('contract_list','Voucher/contract_list');
Route::rule('add_edit_contract','Voucher/add_edit_contract');
Route::rule('add_edit_pay','Voucher/add_edit_pay');
Route::rule('add_edit_payuserlist','Voucher/add_edit_payuserlist');
Route::rule('voucher_update','Voucher/voucher_update');
Route::rule('invoice_update','Voucher/invoice_update');
Route::rule('bq_edit','Items/add_edit_tag');
Route::rule('jianli_list','Items/resume_list');
Route::rule('jianli_dc','Items/export_resume');
Route::rule('jianli_edit/:id','Items/edit_resume');
Route::rule('jianli_sh','Items/resume_update');
Route::rule('xiangmu_list','Items/item_list');
Route::rule('xiangmu_dc','Items/export_item');
Route::rule('xiangmu_edit/:id','Items/edit_item');
Route::rule('jl_xm_gt_list','Items/item_gt_list');
Route::rule('jl_xm_gt_list_dc','Items/export_item_gt');
/********************{content内容管理控制器}********************/
Route::rule('banner','Content/ad_list');
Route::rule('banner_edit/[:ad_id]','Content/add_edit_ad');
Route::rule('gonggao','Content/essay_list');
Route::rule('gonggao_edit/[:id]','Content/add_edit_essay');
Route::rule('xieyi','Content/protocol_list');
Route::rule('xieyi_edit/[:id]','Content/add_edit_protocol');
/********************{report数据管理控制器}********************/
//Route::rule('count_index','Report/index');
//Route::rule('count_order_list','Report/sale_order');
//Route::rule('count_order_top','Report/sale_top');
//Route::rule('count_user_top','Report/user_top');
//Route::rule('count_user_order_list/[:user_id]','Report/user_order');
//Route::rule('count_goods_list/[:goods_id]','Report/sale_list');
//Route::rule('count_user','Report/user');
/********************{system控制器}********************/
Route::get('sys_index/[:inc_type]','System/index');
Route::get('sys_plugin','System/plugin_index');
Route::rule('sys_plugin_edit','System/plugin_edit');
Route::post('sys_handle','System/handle');
Route::rule('sys_icons','System/icons');
Route::rule('sys_clean','System/cleanCache');
/********************{文件上传}********************/
Route::rule('uploadify','Uploadify/upload');
Route::rule('bianjiqi','Ueditor/index');
Route::rule('video_up','Ueditor/videoUp');
Route::rule('image_up','Ueditor/imageUp');
Route::rule('file_up','Ueditor/upFile');
Route::rule('file_list','Uploadify/fileList');
Route::rule('del_file','Uploadify/delupload');
/********************{weixin微信管理控制器}********************/
Route::rule('wx_home','Weixin/index');
Route::rule('wx_set','Weixin/setting');
Route::rule('wx_set_edit/:id','Weixin/setting_save');
Route::rule('wx_users','Weixin/third_user');
Route::rule('wx_caidan','Weixin/wx_menu');
Route::rule('wx_caidan_baocun','Weixin/wx_menu_save');
Route::rule('wx_caidan_pub','Weixin/wx_menu_pub');
Route::rule('wx_caidan_del','Weixin/wx_menu_del');