#!/usr/bin/env php
<?php
namespace think;
// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';
//区分环境变量
$cmdLine = implode(' ', $argv);
$envName='';
if (stripos($cmdLine, '--env')) {
    $name = substr($cmdLine, stripos($cmdLine, '--env')+5);
    $envName = trim($name);
}
if ($envName) {
    // 应用初始化
    (new App())->setEnvName($envName)->console->run();
}else{
    // 应用初始化
    (new App())->console->run();
}