<?php

use think\facade\Route;
/********************{index控制器}********************/
//首页显示数据
Route::rule('request_index_data','IndexApi/index');
Route::rule('request_voucher_data','IndexApi/voucher');
//获取案例列表
Route::rule('get_gonggao_list','IndexApi/get_essay_list');
//案例详情
Route::rule('gonggao_xq','IndexApi/essay_detail');
//搜索记录
Route::rule('search_list','IndexApi/search');
//清空搜索记录
Route::rule('qk_search','IndexApi/empty_search');
//增加搜索记录
Route::rule('add_search','IndexApi/add_search_keyword');
//协议详情
Route::rule('xieyi_xq','IndexApi/protocol_detail');
/********************{items控制器}********************/
//获取项目/简历列表
Route::rule('get_items_list','ItemsApi/get_items');
//获取项目/简历详情
Route::rule('items_xq','ItemsApi/items_detail');
//提交项目/简历沟通过
Route::rule('items_gt','ItemsApi/items_chat');
//项目/简历收藏
Route::rule('items_sc','ItemsApi/items_collect');
//项目/简历收藏列表
Route::rule('items_sc_list','ItemsApi/items_collect_list');
//沟通过列表
Route::rule('items_gt_list','ItemsApi/items_chat_list');
//所有标签列表
Route::rule('get_tags','ItemsApi/get_tags_list');
//发布/编辑简历
Route::rule('edit_user_resume','ItemsApi/edit_resume');
//简历操作
Route::rule('handle_resume','ItemsApi/do_resume');
//发布/编辑项目
Route::rule('edit_user_item','ItemsApi/edit_item');
//项目操作
Route::rule('handle_item','ItemsApi/do_item');
//客服项目/简历操作
Route::rule('kf_handle_item','ItemsApi/kf_do_item');
//获取客服列表
Route::rule('kefu_list','ItemsApi/get_kf_list');
//客服设置在线状态
Route::rule('kefu_online','ItemsApi/kf_set_online');
//联系客服
Route::rule('lx_kefu','ItemsApi/contact_kf');
/********************{common控制器}********************/
//获取地区列表
Route::rule('get_diqu_list','CommonApi/get_region');
//微信小程序获取openId和sessionKey
Route::rule('get_wx_xcx_data','CommonApi/get_wx_xcx_login');
//微信授权手机号
Route::rule('weixin_mobile','CommonApi/wx_mobile');
//登录/客服登录
Route::rule('denglu','CommonApi/do_login');
Route::rule('kf_denglu','CommonApi/do_kf_login');
//注册
//Route::rule('zhuce','CommonApi/register');
//忘记密码
//Route::rule('forget','CommonApi/forget_pwd');
//获取验证码
Route::rule('send_code','CommonApi/get_code');
//上传文件
Route::rule('put_file','CommonApi/upload_file');
/********************{user控制器}********************/
//获取用户信息
Route::rule('user_info','UserApi/get_user_info');
Route::rule('saveVoucher','UserApi/save_voucher');
Route::rule('saveInvoice','UserApi/save_invoice');
Route::rule('payList','UserApi/pay_list');
Route::rule('invoiceList','UserApi/invoice_list');
Route::rule('kfList','UserApi/kf_list');
Route::rule('contractList','UserApi/contract_list');
Route::rule('contractListservice','UserApi/contract_listservice');
Route::rule('contractDetail','UserApi/contract_detail');
Route::rule('contractDetailInvoice','UserApi/contract_detail_invoice');
//资金明细
//Route::rule('zj_list','UserApi/points');
//生成推广码
Route::rule('qr_code','UserApi/code_img');
//编辑用户信息
Route::rule('edit_user_info','UserApi/edit_info');
//提交用户微信号
Route::rule('edit_user_wx','UserApi/edit_weixin');
//编辑银行卡信息
//Route::rule('edit_user_bank','UserApi/edit_bank');
//修改密码
//Route::rule('set-password','UserApi/password');
//修改昵称
//Route::rule('nicheng','UserApi/nickname');
//地址列表
//Route::rule('dizhi_list','UserApi/address_list');
//个人地址
//Route::rule('dizhi_xq','UserApi/address');
//保存地址
//Route::rule('dizhi_save','UserApi/save_address');
//删除地址
//Route::rule('dizhi_del','UserApi/del_address');
//上传头像
Route::rule('touxiang','UserApi/head_pic');
/********************{payApi控制器}********************/
//Route::rule('zhifu/:pay_code/[:order_sn]','PayApi/get_code');
//Route::rule('zhifu_return','PayApi/return_url');//支付宝支付用的
//Route::rule('zhifu_notify/[:pay_code]','WxPayXcx/notify_url');
//Route::rule('zhifu_weixin','PayApi/weixin_return');//微信jsApi支付用的
