<?php
$menus = [
    [
        'title'=> '标签数量',
        'database'=> 'tags',
        'controller'=> 'Items',
        'action'=> 'tag_list',
        'field'=> '1',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-buffer',
        'bg_class'=> 'bg-purple',
    ],
    [
        'title'=> '待审核简历数',
        'database'=> 'items',
        'controller'=> 'Items',
        'action'=> 'resume_list',
        'field'=> ['type','status'],
        'compare'=> ['=','='],
        'compare_field'=> [2,-1],
        'extra'=> 'status',
        'extra_field'=> '-1',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-buffer',
        'bg_class'=> 'bg-purple',
    ],
    [
        'title'=> '简历总数',
        'database'=> 'items',
        'controller'=> 'Items',
        'action'=> 'resume_list',
        'field'=> 'type',
        'compare'=> '=',
        'compare_field'=> 2,
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-buffer',
        'bg_class'=> 'bg-purple',
    ],
    [
        'title'=> '待审核项目数',
        'database'=> 'items',
        'controller'=> 'Items',
        'action'=> 'item_list',
        'field'=> ['type','status'],
        'compare'=> ['=','='],
        'compare_field'=> [1,-1],
        'extra'=> 'status',
        'extra_field'=> '-1',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-buffer',
        'bg_class'=> 'bg-purple',
    ],
    [
        'title'=> '项目数量',
        'database'=> 'items',
        'controller'=> 'Items',
        'action'=> 'item_list',
        'field'=> 'type',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-buffer',
        'bg_class'=> 'bg-purple',
    ],
    [
        'title'=> '广告数量',
        'database'=> 'ad',
        'controller'=> 'Content',
        'action'=> 'ad_list',
        'field'=> '1',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-image',
        'bg_class'=> 'bg-info',
    ],
//    [
//        'title'=> '公告数量',
//        'database'=> 'essay',
//        'controller'=> 'Content',
//        'action'=> 'essay_list',
//        'field'=> '1',
//        'compare'=> '=',
//        'compare_field'=> 1,
//        'extra'=> '',
//        'extra_field'=> '',
//        'count'=> true,
//        'sum_field'=> '',
//        'icon'=> 'mdi-bell-ring',
//        'bg_class'=> 'bg-info',
//    ],
    [
        'title'=> '协议数量',
        'database'=> 'protocol',
        'controller'=> 'Content',
        'action'=> 'protocol_list',
        'field'=> '1',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-file-document',
        'bg_class'=> 'bg-info',
    ],
    [
        'title'=> '用户总数',
        'database'=> 'users',
        'controller'=> 'User',
        'action'=> 'index',
        'field'=> '1',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-account',
        'bg_class'=> 'bg-danger',
    ],
    [
        'title'=> '客服总数',
        'database'=> 'users',
        'controller'=> 'User',
        'action'=> 'index',
        'field'=> 'is_kf',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> 'is_kf',
        'extra_field'=> '1',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-account',
        'bg_class'=> 'bg-danger',
    ],
    [
        'title'=> '冻结用户总数',
        'database'=> 'users',
        'controller'=> 'User',
        'action'=> 'index',
        'field'=> 'is_lock',
        'compare'=> '=',
        'compare_field'=> 1,
        'extra'=> 'is_lock',
        'extra_field'=> '1',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-account',
        'bg_class'=> 'bg-danger',
    ],
    [
        'title'=> '今日访问用户',
        'database'=> 'users',
        'controller'=> 'User',
        'action'=> 'index',
        'field'=> 'last_login',
        'compare'=> '>=',
        'compare_field'=> '%d',
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-account',
        'bg_class'=> 'bg-danger',
    ],
    [
        'title'=> '今日注册用户',
        'database'=> 'users',
        'controller'=> 'User',
        'action'=> 'index',
        'field'=> 'reg_time',
        'compare'=> '>=',
        'compare_field'=> '%d',
        'extra'=> '',
        'extra_field'=> '',
        'count'=> true,
        'sum_field'=> '',
        'icon'=> 'mdi-account',
        'bg_class'=> 'bg-danger',
    ],
];
return $menus;
